name: Deploy Github Pages
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: fetch gh-pages branch
      # source: https://github.com/actions/checkout/issues/578#issuecomment-1586269282
      run: |
        git fetch --unshallow origin gh-pages
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: publish to gh-pages branch
      run: |
          make github
